[package]
name = "Axion"
version = "1.1.0"
edition = "2024"
build = "build.rs"

[[bin]]
name = "axion-compositor"
path = "src/main.rs"

[[bin]]
name = "axion-decorator"
path = "src/decorator_main.rs"

[dependencies]
smithay = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
calloop = "0.14"
bitflags = "2.2.1"
xcursor = "0.3.11"
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["unstable"] }
slint = {version = "1.9", features = ["renderer-software"]}

[build-dependencies]
slint-build = "1.9"