import "../../fonts/Manrope.ttf";
import { Button } from "std-widgets.slint";
// This is the button (for Maximization/Minimization/Close)
export component CusButton inherits VerticalLayout {
    alignment: center;
    padding-right: 5px;
    Button {
        width: 17px;
        height: 17px;
    } 
}

// This is the main window decorator
export component WindowDecorator inherits Rectangle {
    in property <string> window-title: "No Name Provided";
    in property <brush> textColor: rgba(221, 221, 221);
    background: rgba(131, 127, 127, 0.8);
    height: 42px;
    border-top-left-radius: 12px;
    border-top-right-radius: 12px;
    HorizontalLayout {
        Text {
            text: root.window-title;
            color: root.textColor;
            font-size: 19px;
            font-family: "Manrope";
            horizontal-alignment: center;
            vertical-alignment: center;
            wrap: word-wrap;
        }
        padding-right: 12px;
        CusButton {}
        CusButton {}
        CusButton {}

    }
}
/*
// Example window (Will be removed in production)
export component TestPreview inherits Window {
    width: 850px;
    height: 550px;
    background: #222;
    WindowDecorator {
        width: parent.width;  // this is just the width of the window
        window-title: "Name"; // this is the title
        y: 0px;  // top of the window  
    }
}
*/