import "../../fonts/Manrope.ttf";
import { Button } from "std-widgets.slint";

export component CusButton inherits VerticalLayout {
    alignment: center;
    padding-right: 5px;
    Button {
        width: 17px;
        height: 17px;
    } 
}

// Main Window Decorator Element
export component WindowDecorator inherits Rectangle {
    in property <string> window-title: "No Name Provided";
    in property <brush> textColor: rgba(221, 221, 221);
    background: rgba(131, 127, 127, 0.8);
    height: 42px;
    border-top-left-radius: 12px;
    border-top-right-radius: 12px;
    
    HorizontalLayout {
        Text {
            text: root.window-title;
            color: root.textColor;
            font-size: 19px;
            font-family: "Manrope";
            horizontal-alignment: center;
            vertical-alignment: center;
            wrap: word-wrap;
        }
        padding-right: 12px;
        CusButton {}
        CusButton {}
        CusButton {}
    }
}

// Transparent Frame Viewport
export component TestPreview inherits Window {
    in property <string> window-title: "No Name Provided";
    in property <brush> textColor: rgba(221, 221, 221);
    in property <length> w: 500px;
    always-on-top: true;
    no-frame: true;
    
    background: transparent;
    
    width: w;
    height: 42px;

    WindowDecorator {
        width: parent.width;
        height: parent.height;
        window-title: root.window-title;
        textColor: root.textColor;
    }
}
